### ISSUE TITLE
Arithmetic overflow

### ISSUE THREAD

**Issue by no-longer-on-githu-b** [purescript/purescript-prelude#60] opened 2016-02-06 10:24 UTC
The documentation currently does not specify what happens on arithmetic overflow. If the behaviour is not meant to be undefined then it should be specified.

**Comment by michaelficarra** [comment] 2016-02-06 16:09
I think it is meant to be undefined. Overflow or underflow on arithmetic operations is a program error, and I would prefer an immediate halt. Since we have no indication of the event at the JS level, I think the best we can do is leave it undefined.

**Comment by hdgarrood** [comment] 2016-02-06 16:27
I think we could modify the definitions of arithmetic operations for Int so that over/underflow makes the program halt, but I guess that would be an unacceptable performance hit. I think leaving them undefined is fine; if you're worried, use an arbitrary precision int library. I agree that we should probably document this though - perhaps on the Semiring class?

**Comment by michaelficarra** [comment] 2016-02-06 16:33
@hdgarrood How do you detect overflow at the JS level?

**Comment by hdgarrood** [comment] 2016-02-06 16:53
This is a bit pathological, but I'm only trying to show that a method exists, so:

``` purescript
instance semiringInt :: Semiring Int where
  add x y =
    let result = BigInt.fromInt x + BigInt.fromInt y
    in case BigInt.toInt result of
      Just z -> z
      Nothing -> unsafeCrashWith "Int overflow"
```

where `BigInt.toInt :: BigInt -> Maybe Int` returns `Nothing` if the value is outside the `Int` range.

I doubt any practically reasonable method exists, though, which is why I'm happy leaving it undefined.

**Comment by hdgarrood** [comment] 2016-02-07 02:36
Duplicate of #30?

**Closed as completed** 2016-09-26 15:16 UTC
